name: Continuous integration - GYM API

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    service:
      postgres:
        image: bitnami/postgresql:latest
        ports:
          - 5432:5432
        environment:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: 03-api-solid

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.26.2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check lint
        run: pnpm lint:check

      - name: Run unit tests
        run: pnpm test:unit

      # - name: Run E2E tests
      #   run: pnpm test:e2e
      #   env:
      #     SECRET_JWT: my-jwt-secret
      #     DATABASE_URL: postgresql://docker:docker@localhost:5432/03-api-solid?schema=public

      - name: Run prisma generate
        run: pnpm prisma:generate
        env:
          DATABASE_URL: postgresql://docker:docker@localhost:5432/03-api-solid?schema=public

      - name: Run build
        run: pnpm build
